# Generated by Django 4.0.4 on 2022-05-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measure_one',
            new_name='measure_reciver_one',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measure_three',
            new_name='measure_reciver_two',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measure_two',
            new_name='measure_y_one',
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='measure_y_two',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='measure_z_one',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='measure_z_two',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
