# Generated by Django 4.0.4 on 2022-05-27 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_measure_one_measurement_measure_reciver_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measure_reciver_one',
            new_name='measure_acceleration_pitch',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measure_reciver_two',
            new_name='measure_acceleration_total_vector',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measure_y_one',
            new_name='measure_acceleration_yaw',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measure_y_two',
            new_name='measure_angle_pitch',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measure_z_one',
            new_name='measure_angle_yaw',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measure_z_two',
            new_name='measure_reciver_one_rx',
        ),
        migrations.AddField(
            model_name='measurement',
            name='measure_reciver_two_rx',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='timestamp'),
        ),
    ]
